from socket import gethostbyname, gethostname, AF_INET, SOCK_DGRAM

REQUEST_COMMAND = "!REQ"
GRANT_COMMAND = "!GRANT"
DISCONNECT_COMMAND = "!DISC"
RELEASE_COMMAND = "!REL"

CLIENT_ID_IDENTIFIER = "!CLIENT_ID"

SERVER_IP = gethostbyname(gethostname())
SERVER_PORT = 5566
SERVER_ADDRESS = (SERVER_IP, SERVER_PORT)

MESSAGE_HEADER = 64
MESSAGE_SIZE = 1024
MESSAGE_FORMAT = "utf-8"

SOCKET_FAMILY = AF_INET
SOCKET_PROTOCOL = SOCK_DGRAM
